install:
	mkdir -p ${DESTDIR}/usr/share/slackware-live
	cp scripts/init ${DESTDIR}/usr/share/slackware-live/
	mkdir -p ${DESTDIR}/usr/sbin
	cp scripts/build-slackware-live.sh ${DESTDIR}/usr/sbin/
	chmod u+x ${DESTDIR}/usr/sbin/build-slackware-live.sh
	mkdir -p ${DESTDIR}/usr/doc
	cp -r doc ${DESTDIR}/usr/doc/slackware-live-0.4
	